### ISSUE TITLE
Don't show profile link when no URL is available

### ISSUE THREAD

**Issue by olivier5741** [qalincalabs/logcica-explore#11]
There is for instance no link associated with FJA 

![Image](https://github.com/qalincalabs/logcica-explore/assets/3897291/4d649284-02e4-43f8-a9f5-19e98eae6dab)

**Comment by logcica** [comment]
Salut Yassir, je me suis sans doute mal exprimé pour celui-ci.

* Il faut afficher tous les profiles
* Si le profile à un `link`, il faut qu'il s'affiche comme un lien (icône + jaune + sous ligné) sinon l'afficher comme du texte normal

**Comment by ysrhad03** [comment]
d'accord dès que je termine ma tâche je vais corriger le code
